######################################
#
# BUSCO summary figure
# @author Mathieu Seppey <mathieu.seppey@unige.ch>
# @version 2.0
# @since BUSCO 2.0
# 
# Copyright (C) 2016 E. Zdobnov lab
# 
# BUSCO is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version. See <http://www.gnu.org/licenses/>
#  
# BUSCO is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
######################################

# Load the required libraries
library(ggplot2)
library("grid")

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("/projectnb/mullenl/kate/annotated_trinity_assemblies/plot_data/","busco_figure.png",sep="/") 
my_width <- 20
my_height <- 30
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- "BUSCO Assessment Results"

# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('SF68', 'SF68', 'SF68', 'SF68', 'SF49', 'SF49', 'SF49', 'SF49', 'SF19', 'SF19', 'SF19', 'SF19', 'SF57', 'SF57', 'SF57', 'SF57', 'SF18', 'SF18', 'SF18', 'SF18', 'SF39', 'SF39', 'SF39', 'SF39', 'SF31', 'SF31', 'SF31', 'SF31', 'SF05', 'SF05', 'SF05', 'SF05', 'SF52', 'SF52', 'SF52', 'SF52', 'SF60', 'SF60', 'SF60', 'SF60', 'SF06', 'SF06', 'SF06', 'SF06', 'SF27', 'SF27', 'SF27', 'SF27', 'SF72', 'SF72', 'SF72', 'SF72', 'SF37', 'SF37', 'SF37', 'SF37', 'SF21', 'SF21', 'SF21', 'SF21', 'SF28', 'SF28', 'SF28', 'SF28', 'SF73', 'SF73', 'SF73', 'SF73', 'SF09', 'SF09', 'SF09', 'SF09', 'SF38', 'SF38', 'SF38', 'SF38', 'SF36', 'SF36', 'SF36', 'SF36', 'SF59', 'SF59', 'SF59', 'SF59', 'SF02', 'SF02', 'SF02', 'SF02', 'SF03', 'SF03', 'SF03', 'SF03', 'SF23', 'SF23', 'SF23', 'SF23', 'SF46', 'SF46', 'SF46', 'SF46', 'SF67', 'SF67', 'SF67', 'SF67', 'SF10', 'SF10', 'SF10', 'SF10', 'SF16', 'SF16', 'SF16', 'SF16', 'SF15', 'SF15', 'SF15', 'SF15', 'SF64', 'SF64', 'SF64', 'SF64', 'SF56', 'SF56', 'SF56', 'SF56', 'SF24', 'SF24', 'SF24', 'SF24', 'SF41', 'SF41', 'SF41', 'SF41', 'SF29', 'SF29', 'SF29', 'SF29', 'SF17', 'SF17', 'SF17', 'SF17', 'SF61', 'SF61', 'SF61', 'SF61', 'SF30', 'SF30', 'SF30', 'SF30', 'SF42', 'SF42', 'SF42', 'SF42', 'SF44', 'SF44', 'SF44', 'SF44', 'SF22', 'SF22', 'SF22', 'SF22', 'SF14', 'SF14', 'SF14', 'SF14', 'SF12', 'SF12', 'SF12', 'SF12', 'SF71', 'SF71', 'SF71', 'SF71', 'SF63', 'SF63', 'SF63', 'SF63', 'SF07', 'SF07', 'SF07', 'SF07', 'SF11', 'SF11', 'SF11', 'SF11', 'SF26', 'SF26', 'SF26', 'SF26', 'SF34', 'SF34', 'SF34', 'SF34', 'SF69', 'SF69', 'SF69', 'SF69', 'SF50', 'SF50', 'SF50', 'SF50', 'SF65', 'SF65', 'SF65', 'SF65', 'SF62', 'SF62', 'SF62', 'SF62', 'SF32', 'SF32', 'SF32', 'SF32', 'SF55', 'SF55', 'SF55', 'SF55', 'SF20', 'SF20', 'SF20', 'SF20', 'SF43', 'SF43', 'SF43', 'SF43', 'SF08', 'SF08', 'SF08', 'SF08', 'SF01', 'SF01', 'SF01', 'SF01', 'SF25', 'SF25', 'SF25', 'SF25', 'SF04', 'SF04', 'SF04', 'SF04', 'SF53', 'SF53', 'SF53', 'SF53', 'SF48', 'SF48', 'SF48', 'SF48', 'SF70', 'SF70', 'SF70', 'SF70', 'SF33', 'SF33', 'SF33', 'SF33', 'SF51', 'SF51', 'SF51', 'SF51', 'SF58', 'SF58', 'SF58', 'SF58', 'SF45', 'SF45', 'SF45', 'SF45', 'SF66', 'SF66', 'SF66', 'SF66', 'SF13', 'SF13', 'SF13', 'SF13', 'SF40', 'SF40', 'SF40', 'SF40', 'SF35', 'SF35', 'SF35', 'SF35')
my_species <- factor(my_species)
my_species <- factor(my_species,levels(my_species)[c(length(levels(my_species)):1)]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(51.7, 31.6, 12.2, 4.5, 44.0, 29.9, 20.3, 5.8, 49.0, 25.9, 19.2, 5.9, 45.2, 24.2, 24.0, 6.6, 44.9, 28.4, 20.3, 6.4, 47.6, 24.8, 21.2, 6.4, 47.3, 24.2, 20.1, 8.4, 48.0, 16.5, 25.9, 9.6, 44.6, 16.0, 28.2, 11.2, 49.7, 28.5, 16.6, 5.2, 46.3, 22.0, 23.1, 8.6, 37.8, 13.8, 31.1, 17.3, 45.1, 27.4, 21.4, 6.1, 48.2, 22.5, 20.8, 8.5, 40.7, 20.5, 28.1, 10.7, 41.2, 16.1, 29.0, 13.7, 43.1, 27.0, 23.0, 6.9, 33.0, 20.7, 30.5, 15.8, 49.6, 24.2, 20.3, 5.9, 40.8, 24.2, 24.7, 10.3, 44.3, 26.0, 22.4, 7.3, 40.8, 14.3, 30.0, 14.9, 47.9, 25.0, 20.7, 6.4, 38.2, 18.8, 30.9, 12.1, 51.1, 31.8, 13.1, 4.0, 36.1, 22.3, 29.0, 12.6, 34.6, 18.9, 33.0, 13.5, 46.9, 28.2, 18.3, 6.6, 43.0, 23.0, 24.7, 9.3, 52.1, 23.3, 18.6, 6.0, 49.2, 24.8, 19.8, 6.2, 42.3, 17.9, 28.3, 11.5, 45.5, 25.1, 21.7, 7.7, 47.7, 17.1, 24.8, 10.4, 45.9, 27.3, 20.2, 6.6, 46.6, 25.1, 22.1, 6.2, 46.0, 16.3, 26.1, 11.6, 44.5, 25.5, 23.2, 6.8, 43.4, 18.2, 25.7, 12.7, 40.0, 16.1, 29.8, 14.1, 43.4, 28.3, 22.0, 6.3, 41.1, 26.5, 23.6, 8.8, 47.0, 23.9, 21.6, 7.5, 48.6, 29.6, 16.8, 5.0, 26.4, 15.1, 38.6, 19.9, 39.0, 20.5, 30.3, 10.2, 36.1, 14.5, 34.1, 15.3, 40.1, 20.7, 28.1, 11.1, 39.7, 21.5, 27.2, 11.6, 52.7, 25.5, 17.1, 4.7, 42.3, 30.6, 20.8, 6.3, 48.9, 30.2, 16.3, 4.6, 47.2, 20.6, 22.1, 10.1, 39.3, 29.7, 23.2, 7.8, 44.8, 22.5, 24.1, 8.6, 46.7, 25.3, 20.9, 7.1, 27.6, 12.1, 36.8, 23.5, 54.2, 29.6, 12.5, 3.7, 38.7, 22.2, 29.3, 9.8, 49.2, 20.3, 21.5, 9.0, 51.7, 28.2, 15.3, 4.8, 50.7, 23.5, 18.8, 7.0, 50.8, 23.5, 18.9, 6.8, 39.9, 18.9, 29.3, 11.9, 47.5, 27.9, 18.8, 5.8, 46.4, 29.2, 18.8, 5.6, 52.2, 24.3, 17.6, 5.9, 43.2, 28.1, 21.7, 7.0, 42.7, 20.4, 27.4, 9.5, 41.1, 18.8, 26.2, 13.9, 42.4, 23.9, 25.0, 8.7)
my_values <- c(858, 524, 202, 74, 729, 495, 336, 98, 813, 430, 318, 97, 749, 401, 398, 110, 745, 471, 337, 105, 789, 412, 352, 105, 785, 401, 333, 139, 796, 273, 429, 160, 739, 265, 467, 187, 824, 472, 275, 87, 768, 364, 383, 143, 626, 228, 515, 289, 748, 454, 354, 102, 799, 373, 345, 141, 674, 340, 466, 178, 683, 267, 481, 227, 714, 448, 381, 115, 547, 344, 506, 261, 822, 401, 337, 98, 676, 401, 409, 172, 735, 431, 372, 120, 676, 237, 498, 247, 794, 415, 343, 106, 633, 311, 513, 201, 847, 527, 217, 67, 598, 369, 480, 211, 574, 314, 547, 223, 778, 468, 304, 108, 713, 382, 410, 153, 863, 387, 309, 99, 816, 411, 328, 103, 701, 297, 469, 191, 755, 416, 360, 127, 791, 284, 412, 171, 761, 452, 335, 110, 772, 416, 367, 103, 762, 270, 432, 194, 738, 423, 385, 112, 720, 302, 426, 210, 664, 267, 494, 233, 720, 470, 364, 104, 682, 440, 392, 144, 779, 397, 358, 124, 806, 491, 278, 83, 437, 251, 640, 330, 647, 340, 502, 169, 598, 240, 566, 254, 665, 344, 466, 183, 658, 357, 451, 192, 873, 422, 284, 79, 701, 507, 345, 105, 811, 501, 271, 75, 782, 341, 367, 168, 651, 493, 384, 130, 742, 373, 399, 144, 774, 419, 346, 119, 458, 201, 610, 389, 899, 490, 208, 61, 641, 368, 485, 164, 815, 336, 357, 150, 857, 468, 254, 79, 840, 389, 312, 117, 843, 389, 314, 112, 661, 314, 486, 197, 788, 463, 312, 95, 770, 484, 311, 93, 866, 403, 291, 98, 717, 466, 360, 115, 708, 338, 455, 157, 682, 311, 435, 230, 703, 396, 414, 145)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(plot.title = element_text(family=my_family, colour = "black", size = rel(2.2)*my_size_ratio, face = "bold")) + 
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(size=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }
  
ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)
print("Done")
